/* This file is generated by venus-protocol git-2c678af3. */

/*
 * Copyright 2020 Google LLC
 * SPDX-License-Identifier: MIT
 */

#ifndef VN_PROTOCOL_RENDERER_H
#define VN_PROTOCOL_RENDERER_H

#pragma GCC diagnostic push

#pragma GCC diagnostic ignored "-Wpointer-arith"
#pragma GCC diagnostic ignored "-Wunused-parameter"

#include "vn_protocol_renderer_cs.h"
#include "vn_protocol_renderer_defines.h"
#include "vn_protocol_renderer_info.h"
#include "vn_protocol_renderer_types.h"
#include "vn_protocol_renderer_handles.h"
#include "vn_protocol_renderer_structs.h"
#include "vn_protocol_renderer_commands.h"
#include "vn_protocol_renderer_dispatches.h"

#pragma GCC diagnostic pop

#endif /* VN_PROTOCOL_RENDERER_H */
